# Generated by Django 3.0.4 on 2020-08-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_contact_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
