# Generated by Django 3.0.4 on 2020-08-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20200819_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='details',
        ),
    ]
